[package]
name = "random_forest"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
deltaml = { path = "../../../delta", features = ["classical"] }
tokio = { workspace = true, features = ["full"] }
